### PR TITLE
Add Karma runner and BrowserStack testing

### PR DESCRIPTION
**Pull request by phuu**
PR for #16, superseding #53.

#### Karma Runner
[Karma](https://karma-runner.github.io/) facilitates the configuration for  adding extra services to the testing process. In this case adding BrowserStack testing was just a matter of installing [karma-browserstack-launcher](https://github.com/karma-runner/karma-browserstack-launcher) and adding a config file.

#### BrowserStack
karma-browserstack-launcher expects `BROWSERSTACK_USERNAME` and `BROWSERSTACK_KEY` environment variables to be set for BrowserStack authentication.

These can be acquired in the BrowserStack [account settings page](https://www.browserstack.com/accounts/settings) at the bottom **Automate** section:

browserstack_automate

And added in the Travis repo settings page at the **Environment Variables** section:

travis_environment_vars

BrowserStack [Browsers & Mobile Devices for JavaScript Testing](https://www.browserstack.com/list-of-browsers-and-platforms?product=js_testing)

#### Testing Configuration
The files for testing configuration are in `./testing/`. All in TypeScript for linting, and compiled by the npm script `build-conf` (I haven't found a way to pipe tsc directly to karma without creating files).

### CODE REVIEW

**Comment by phuu** [comment]
Just added some Browserstack keys to the Travis job.

**Comment by phuu** [comment]
Plan:

- Going to merge this, causing a broken `karma` branch
- Will make @thelambdaparty a collaborator on this repo
- Will start opening PRs into the karma branch so we can work together on getting this ready to go into master

**Comment by phuu** [comment]
@thelambdaparty This squashed your commits into one, but removed your authorship. I'm really sorry about that — totally unintentional. Will try to set the author back to you and force push to the branch.

**Comment by thelambdaparty** [comment]
:smile: no problem

**Pull request merged**
