### PR TITLE
Update README with new `fetchEngine` behaviour.

### LINKED ISSUE #45: Document that fetchEngine is a function, not a constructor
The README is p out of date.

Specifically, `fetch-engine` is now called as a normal function, and passed a `FetchGroup`, or an object that can be passed to a `FetchGroup`:

```js
var fetch = fetchEngine(new FetchGroup({ ... }));
```

### PR DESCRIPTION
**Pull request by jackfranklin**
Closes #45.

### CODE REVIEW

**Comment by phuu** [comment]
Quick feedback: angular commit style pls (https://gist.github.com/stephenparish/9941e89d80e2bc58a153)

`docs: blah` probably.

**Comment by phuu** [comment]
(Otherwise, looks fab)

**Comment by jackfranklin** [comment]
Ah apologies, didn't spot the committing. I shall reformat.

**Comment by jackfranklin** [comment]
@phuu howsat?

**Comment by phuu** [comment]
Loverly, thanks.

**Pull request merged**
