### PR TITLE
feat: add Karma runner and BrowserStack testing

### PR DESCRIPTION
**Pull request by phuu**
- [x] Get the build passing in electron
- [x] Get the build passing on travis
- [ ] Get the build passing on browserstack
- [ ] Get the build passing on all required browsers

### CODE REVIEW

**Comment by phuu** [comment]
@thelambdaparty I think you're able to push to this branch. My suggestion is that we use a rebase workflow on this branch until it's mergable:

Something like this (untested):

```
$ git remote add phuu https://github.com/phuu/fetch-engine
$ git branch -D karma
$ git fetch phuu karma
$ git checkout karma
... do some work & commit ...
$ git pull --rebase
$ git push
```

**Comment by phuu** [comment]
I'm going to try to get it passing on Browserstack consistently before pushing any more — would like to avoid broken builds on this branch.

**Comment by phuu** [comment]
Hmm. There are some of complications here:

- This module should work in node and the browser, so we need to be selective about which tests we run where. Unsure how to do this right now.
- The change to use karma means we're missing some tests. Updating the karma glob to `dist/**/*.test.js` doesn't work and I'm not sure why, so I'm going to look at other options for compiling
- fetch-engine shouldn't bundle it's own Promise implementation — its has to be bring-your-own so that users can choose to polyfill or not, depending on their use case. For testing in browsers, we need to add that polyfill to the global scope manually. Do you know how to configure webpack to add it?
- I also see the Browserstack disconnections and they're a bit worrying. I don't really trust the karma runner tbh — it's just a bit magical. Not sure what do do about that either.

**Comment by thelambdaparty** [comment]
I was able to fix all of those problems, except for the disconnections (which is the most important one :sweat:).

Seems like a problem with karma, because i also tried with [sauce labs](https://saucelabs.com/) and it had the same disconnections. I watched the test going on browserstack and it keeps waiting for a response from the test server (when it's ready to run tests), so it's surely something with the karma-browserstack-launcher.

I saw the manual-browserstack branch. I'll wait for your development there, if it goes well we can just drop this branch, as you'll have more control and config options with that setup.

**Comment by phuu** [comment]
@thelambdaparty What do you think of this: https://github.com/phuu/fetch-engine/pull/64 ?

**Comment by phuu** [comment]
Going to close this because #64 is looking like the way forward. Thanks for your work here @thelambdaparty!

**Pull request closed without merging**
